### ISSUE TITLE
Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by seanfuture** [hukuuu/weather-cli#1]
Currently getting an error as listed below.  Inputs were "atlanta" as the city and a valid API key:

$ weathercli
/usr/lib/node_modules/weathercli/lib/fetch.js:32
      body.list.forEach(function(weather) {
               ^

TypeError: Cannot read property 'forEach' of undefined
    at Request._callback (/usr/lib/node_modules/weathercli/lib/fetch.js:32:16)
    at Request.self.callback (/usr/lib/node_modules/weathercli/node_modules/request/request.js:199:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/lib/node_modules/weathercli/node_modules/request/request.js:1036:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/weathercli/node_modules/request/request.js:963:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:441:9)
    at process._tickCallback (node.js:355:17)
seanfuture@FutureCloud-002:~$

**Comment by nkaradzhov** [comment]
yes, seems like the api isnt responding as expected, thanks, i will check it

**Comment by nickolayrusev** [comment]
+1
